docs(Header): write docs
consta-design-system/header pull request #1
Opened 2022-01-19 12:39 UTC by arhayka

Добавила документацию для некоторых компонентов. Описала принципы работы.

2022-01-20 12:16 UTC, gizeasy requested changes

2022-01-20 12:16 UTC, gizeasy commented on src/Header/__stories__/Header.docs.mdx
> +Добавить пункты меню можно с помощью свойства `menu`, подробности — в документации компонента [MobileMenu](?path=/docs/components-mobilemenu--playground).
Думаю стоит ссылку на `Menu` оставить, но api у `MobileMenu` и `Menu` не отличается

2022-01-20 12:16 UTC, gizeasy commented on src/Menu/__stories__/Menu.docs.mdx
> +  - [Содержимое](#содержимое)
ссылка ни куда не ведет

2022-01-24 17:15 UTC, arhayka commented on src/Badges/__stories__/examples/BadgesExample.tsx
> +    <Badges style={{ marginBottom: 'var(--space-s)' }} items={items} form="default" />
не работает) делаю так:

import { cnMixSpace } from '@consta/uikit/MixSpace'

<Badges className={cnMixSpace({mB: 'l'})} items={items} form="default" />

Стиль подхватывается, отступа нет) Что я делаю не так?

2022-01-26 11:22 UTC, merged