feat(megamenu): add new compoenent
consta-design-system/header pull request #38
Opened 2023-01-11 09:09 UTC by N1MBER

closes consta-design-system/uikit#2779

2023-01-12 14:38 UTC, gizeasy requested changes

2023-01-12 14:38 UTC, gizeasy commented on src/components/BannerBar/BannerBar.css
> +.che--BannerBar {
![image](https://user-images.githubusercontent.com/13190808/212088135-1f42f2aa-e9eb-497d-aae6-88aea8e91a59.png)

во многих местах всречаюся кнопки без оступов, это норм?

2023-01-12 14:38 UTC, gizeasy commented on src/components/NavBar/NavBar.tsx
> +const NavBarRender = (props: NavBarProps, ref: React.Ref<HTMLDivElement>) => {
![image](https://user-images.githubusercontent.com/13190808/212088684-33862866-3050-4619-9de9-355ba2c8e078.png)

думаю теперь стоит использовать `List`

2023-01-12 14:38 UTC, gizeasy commented on src/components/MegaMenu/useComponentBreakpoints.ts
> +
взять из uikit

2023-01-12 14:38 UTC, gizeasy commented on src/components/GlobalMenu/GlobalMenu.tsx
> +          className={cnGlobalMenu('Title')}
как думаешь может в местах там где, сили нужны толко для отступов использовать миксин `MixSpace`?

2023-01-12 14:38 UTC, gizeasy commented on src/components/BannerBar/BannerBar.css
> +  width: 100%;
давай не будем растягивать его по умолчанию, давай в конкретном месте исползования заниматся позиционированием

2023-01-12 14:38 UTC, gizeasy commented on src/components/GlobalMenu/GlobalMenu.css
> +.che--GlobalMenu {
![image](https://user-images.githubusercontent.com/13190808/212094149-1d28ad38-45cc-4161-a2e3-02a8d5998eb2.png)

норм что отступов нет?

может на листе собрать?

2023-01-12 14:38 UTC, gizeasy commented on src/components/MegaMenu/MegaMenu.css
> +        --mega-menu-transform: translate3d(-100%, 0, 0);
слишком длинный путь анимации, сократи его до 20%

2023-01-12 14:38 UTC, gizeasy commented on src/components/MegaMenu/__stand__/examples/MegaMenuExample/MegaMenuExample.tsx
> +const getSubMenu = (prefix?: string) => [
давай в контент ттоже этот префикс добавим, чтоб было заметно что происходит переключение, хотя бы у одного раздела

2023-01-13 06:40 UTC, Lyubavskaya commented
![image](https://user-images.githubusercontent.com/75978078/212254303-e5ec508d-b232-4003-b43c-274de71822d4.png)

2023-01-13 06:45 UTC, Lyubavskaya commented
При увеличении значения menuMaxElements на витрине ничего не меняется

2023-01-13 06:48 UTC, Lyubavskaya commented
Не забыть проставить правильную версию 
![image](https://user-images.githubusercontent.com/75978078/212255438-beeae7bd-37d4-455b-880e-c0f3eb3d35eb.png)

2023-01-13 07:54 UTC, gizeasy requested changes
![image](https://user-images.githubusercontent.com/13190808/212266624-71ec9bf8-8833-40be-99ec-6cf392674137.png)

в вариантах меню при полном экране не разворачивается

еще стоит сделать пример сунув этот компонент в лаяут

![image](https://user-images.githubusercontent.com/13190808/212267073-3b4a666e-ab0a-4fac-83df-b0bf1e56de68.png)

а при не развернутом окна вариантов контент под меню не виден

2023-01-19 18:44 UTC, BagenovA requested changes

2023-01-19 18:44 UTC, BagenovA commented on src/components/MegaMenu/__stand__/MegaMenu.dev.stand.mdx
> +Если поля `subMenu` у элементов нет, то будет ренериться только [`NavBar`](##LIBS.LIB.STAND/lib:header/stand:components-navbar-canary), если есть и уровень вложенности 1, то будет рендериться [`NavBa
Если я правильно поняла, то так:

Если у элементов нет поля `subMenu`, то рендериться будет только [`NavBar`]. Если есть уровень вложенности 1, то рендериться будет [`NavBar`]. В ином случае оба компонента сразу.

2023-01-19 18:44 UTC, BagenovA commented on src/components/MegaMenu/__stand__/MegaMenu.dev.stand.mdx
> +| `isOpen?`               | `boolean`                         | -                             | Флаг открыто ли меню                                                    |
Может так: Возвращает состояние меню: открыто/закрыто

2023-01-19 18:44 UTC, BagenovA commented on src/components/MegaMenu/__stand__/MegaMenu.dev.stand.mdx
> +| `onItemClick?`          | `MegaMenuPropOnItemClick`         | -                             | Событие по нажаьию на элемент                                           |
Исправить опечатку в слове "нажатию"

2023-01-19 18:44 UTC, BagenovA commented on src/components/MegaMenu/__stand__/MegaMenu.dev.stand.mdx
> +| `onBannerClick?`        | `MegaMenuPropOnItemClick`         | -                             | Событие по нажаьию на баннер                                            |
Исправить опечатку в слове "нажатию"

2023-01-19 18:44 UTC, BagenovA commented on src/components/MegaMenu/__stand__/MegaMenu.dev.stand.mdx
> +| `getItemAs?`            | `MegaMenuPropGetItemAs`           | `defaultGetItemAs`            | Функция для определения тэга элемента                                   |
Слово "тэг" исправить на "тег"

2023-01-19 18:44 UTC, BagenovA commented on src/components/MegaMenu/__stand__/MegaMenu.dev.stand.mdx
> +| `getBannerDescription?` | `BannerBarPropGetItemDescription` | `defaultGetBannerDescription` | Функция для определения заголовка элемента                              |
Здесь и до className в описании свойств дублируется текст из getBannerLabel

2023-01-19 18:44 UTC, BagenovA commented on src/components/MegaMenu/__stand__/MegaMenu.stand.mdx
> +MegaMenu - боковое меню
Может лучше так: Выпадающее боковое меню, где вложенное меню включает в себя множество пунктов, разбитых на колонки

2023-01-20 08:12 UTC, BagenovA requested changes

2023-01-20 08:12 UTC, BagenovA commented on src/components/MegaMenu/__stand__/MegaMenu.dev.stand.mdx
> +Если у элементов нет поля `subMenu`, то будет ренериться только [`NavBar`](##LIBS.LIB.STAND/lib:header/stand:components-navbar-canary). Если есть уровень вложенности 1, то рендериться будет [`GlobalM
Исправить опечатку в слове рендериться (возле NavBar).

2023-01-25 14:20 UTC, BagenovA requested changes

2023-01-25 14:20 UTC, BagenovA commented on src/components/MegaMenu/__stand__/MegaMenu.dev.stand.mdx
> +Для того чтобы ваш компонент имел оверлей, а также абсолютное позиционирование с анимацией необходимо использовать компонент `MegaMenuBox`.
Исправить на: Для того, чтобы ваш компонент имел оверлей, а также абсолютное позиционирование с анимацией, необходимо использовать компонент MegaMenuBox.

2023-01-25 14:20 UTC, BagenovA commented on src/components/MegaMenu/__stand__/MegaMenu.dev.stand.mdx
> +> Так как пример позиционируется абсолютно сверху, он будет находится сверху страницы
Может так: Так как пример позиционируется абсолютно сверху, он будет находиться вверху страницы.

2023-01-25 14:20 UTC, BagenovA commented on src/components/MegaMenu/__stand__/examples/MegaMenuBoxExample/MegaMenuBoxExample.tsx
> +        label: 'ГорнозаводскаяГорнозаводская',
Убрать дубль

2023-01-25 14:20 UTC, BagenovA commented on src/components/MegaMenu/__stand__/examples/MegaMenuBoxExample/MegaMenuBoxExample.tsx
> +    label: 'Трубопровод',
Может "Трубопроводы"?

2023-01-25 14:20 UTC, BagenovA commented on src/components/MegaMenu/__stand__/examples/MegaMenuBoxExample/MegaMenuBoxExample.tsx
> +    label: 'Перерабатывающие завводы',
Исправить опечатку в слове "заводы"

2023-01-25 14:20 UTC, BagenovA commented on src/components/MegaMenu/__stand__/examples/MegaMenuExample/MegaMenuExample.tsx
> +        label: 'ГорнозаводскаяГорнозаводская',
Убрать дубль (здесь и везде, где есть этот пример)

2023-01-25 14:20 UTC, BagenovA commented on src/components/MegaMenu/__stand__/examples/MegaMenuExample/MegaMenuExample.tsx
> +    label: 'Трубопровод',
Исправить на "Трубопроводы" (здесь и везде, где есть этот пример)

2023-01-25 14:20 UTC, BagenovA commented on src/components/MegaMenu/__stand__/examples/MegaMenuExample/MegaMenuExample.tsx
> +    label: 'Перерабатывающие завводы',
Исправить опечатку в слове "заводы" (здесь и везде, где есть этот пример)

2023-01-25 14:20 UTC, BagenovA commented on src/components/MegaMenu/__stand__/MegaMenu.dev.stand.mdx
> +- [Обертка](#обертка)
Исправить на "Обёртка"

2023-01-25 14:29 UTC, gizeasy requested changes

2023-01-25 14:29 UTC, gizeasy commented on src/components/MegaMenu/MegaMenu.tsx
> +  const columns = getLastPoint(
Из-за того что `globalMenuRef` находится в условии и может быть `null` не всегда верно считается `columns`

предлагаю  расчитываение колонок поместить в `GlobalMenu` пусть он отвечает за то сколько колонок рисовать.

2023-01-25 14:29 UTC, gizeasy commented on src/components/MegaMenu/MegaMenu.tsx
> +  const columns = getLastPoint(
columns по умолчанию `auto` или можно свое значение прокинуть

2023-01-25 17:01 UTC, merged